### ISSUE TITLE
Hi error messages not showing

### ISSUE THREAD

**Issue by danieldflrss** [ShabanKamell/SwiftUIFormValidator#1]
I added an array of validations how is it: 

```
lazy var firstNameValidation: ValidationContainer = {
        let validators: [StringValidator] = [
            CountValidator(count: 6, type: .greaterThanOrEquals),
            PrefixValidator(prefix: "st.")
        ]
        return $username.allValid(validators: validators, form: form)
    }()
```

and run manual trigger validation, then the message error not show

`form.triggerValidation()
`

my form
@Published var form = FormValidation(validationType: .immediate)

only show error when value changed

**Comment by ShabanKamell** [comment]
Dear Daniel,

Thanks for your report. Kindly be informed that it's now fixed in version` 0.12.4`.

Thanks
