### ISSUE TITLE
Invalid Exclude - 2 files not found

### ISSUE THREAD

**Issue by JulesMoorhouse** [ShabanKamell/SwiftUIFormValidator#2]
```
Invalid Exclude '/Users/me/Library/Developer/Xcode/DerivedData/snip/SourcePackages/checkouts/
SwiftUIFormValidator/Sources/Examples': File not found.

Invalid Exclude '/Users/me/Library/Developer/Xcode/DerivedData/snip/SourcePackages/
checkouts/SwiftUIFormValidator/Sources/Tests': File not found.
```

I've added the package and I'm getting these warnings...

I'm using Xcode 13.2.1

I think it's just that the `Sources` folder isn't required..
`Tests` and `Examples` appear in the parent folder.

Best regards,

Jules.

**Comment by ShabanKamell** [comment]
Dear Jules,

Thanks for your report. It's now fixed in version `0.12.3`.

Thanks
