### ISSUE TITLE
Feature Request: validation view modifier that accepts nil

### ISSUE THREAD

**Issue by JulesMoorhouse** [ShabanKamell/SwiftUIFormValidator#3]
It would be awesome if the `validation` view modifier accepted nil for conditional validation could be used...

e.g.

<img width="879" alt="suggestion" src="https://user-images.githubusercontent.com/361024/149663493-350fb604-eae3-4d56-a8ca-0a5f5a149faf.png">

I have common functionality where I'd like to use this

**Comment by ShabanKamell** [comment]
Thanks Jules for the feature request. It's now implemented in version `0.13.0`.
