### ISSUE TITLE
View Handling it's own validation UI

### ISSUE THREAD

**Issue by chriskilpin** [ShabanKamell/SwiftUIFormValidator#5]
Hi There

Thanks for sharing a great project. Would it be possible to allow a view to handle its own validation UI via a binding instead of putting an error message underneath view via the viewmodifier?  For my use case I would like to change the text colour of the input and apply a red stroke around it in addition to showing the error message underneath.

Thanks!

**Comment by ShabanKamell** [comment]
Hi Christopher,

Thanks for you motivating words and I'm happy that the project helped you 🙏

I have released a new version `0.14.0`, in which I have provided an option to customize the error view. Kindly check
https://github.com/ShabanKamell/SwiftUIFormValidator#custom-error-view

And I have added an example demonstrating the ability to display the error view in any place you need. Kindly check
https://github.com/ShabanKamell/SwiftUIFormValidator/blob/master/Example/RoundedTextField.swift

Regards

**Comment by chriskilpin** [comment]
Thanks for getting back to me, will test it out now!

Regards
