### ISSUE TITLE
The following build commands failed: PhaseScriptExecution

### ISSUE THREAD

**Issue by keerthankrrao** [ShabanKamell/SwiftUIFormValidator#7]
Hi, I'm facing an error while using the SwiftUIFormValidator library during Azure DevOp Pipeline building process. 

I'm currently developing an app using Kotlin MultiPlatform Mobile.

I'm using SwiftUIFormValidator for form validations in iOS.

I'm able to build it successfully in local machine but not in Azure DevOps Pipeline.

Here's the error log.

Running script '[CP-User] Build shared' ▸ Processing SwiftUIFormValidator-Info.plist ** BUILD FAILED **

The following build commands failed: PhaseScriptExecution [CP-User]\ Build\ shared /Users/runner/Library/Developer/Xcode/DerivedData/iosApp-dongzyrxhgtfzxexzqjllvyjwgcu/Build/Intermediates.noindex/Pods.build/Release-iphoneos/shared.build/Script-4552119A071AC6BAB7327E6434237EC3.sh (in target 'shared' from project 'Pods')

Kindly let me know the solution for the above error. Thank you.

**Comment by ShabanKamell** [comment]
Hi,

I've checked the logs, and it looks like the problem is with Pods. I recommend setting up CocoaPods on Azure before starting the build process.

**Comment by ShabanKamell** [comment]
Also instead of CocoaPods, you can use Swift Package Manager.
